# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Stefanini-desafio-app' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Stefanini-desafio-app
    pod 'SDWebImage', '~> 4.0'

  target 'Stefanini-desafio-appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Stefanini-desafio-appUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
